Repository dunsuite/dunchat, pull requests merged in 2025-02, with the labels that each got.

#9 Setup drizzle with postgres for api
  backend/bun.lock
  backend/drizzle.config.ts
  backend/package.json
  backend/src/db/index.ts
  backend/src/db/schema.ts
  backend/tsconfig.json
Labels: api

#7 Refactor authentication and database schema with improved user manage…
  app/bun.lock
  app/drizzle/0000_far_baron_strucker.sql
  app/drizzle/meta/0000_snapshot.json
  app/drizzle/meta/_journal.json
  app/package.json
  app/src/lib/server/auth.ts
  app/src/lib/server/db/schema.ts
  app/src/routes/+page.server.ts
  app/src/routes/+page.svelte
  app/src/routes/demo/+page.svelte
  app/src/routes/demo/lucia/+page.svelte
  app/src/routes/login/+page.server.ts
  app/src/routes/login/+page.svelte
Labels: core

#15 Implement sign up and login flow
  backend/bun.lock
  backend/drizzle/0000_worried_outlaw_kid.sql
  backend/drizzle/meta/0000_snapshot.json
  backend/drizzle/meta/_journal.json
  backend/package.json
  backend/src/api/users/index.ts
  backend/src/db/index.ts
  backend/src/db/schema.ts
  backend/src/index.ts
  backend/src/middleware/index.ts
  backend/src/utils/error.ts
  backend/src/utils/nanoid.ts
  backend/src/utils/validate-password.ts
Labels: api

#17 Add Tailwind CSS configuration and implement workspace creation with invitations
  app/bun.lock
  app/components.json
  app/drizzle/0001_watery_praxagora.sql
  app/drizzle/meta/0001_snapshot.json
  app/drizzle/meta/_journal.json
  app/package.json
  app/postcss.config.js
  app/src/app.css
  app/src/lib/server/db/schema.ts
  app/src/lib/utils/tailwind.ts
  app/src/routes/workspace/create/+error.svelte
  app/src/routes/workspace/create/+page.server.ts
  app/src/routes/workspace/create/+page.svelte
  app/svelte.config.js
  app/tailwind.config.ts
Labels: core

#20 Setup landing page (Marketing)
  landing/bun.lock
  landing/package.json
  landing/src/app.css
  landing/src/lib/components/misc/footer.svelte
  landing/src/lib/components/misc/gradient.svelte
  landing/src/lib/components/misc/index.ts
  landing/src/lib/components/sections/home/explainer-section.svelte
  landing/src/lib/components/sections/home/hero-section.svelte
  landing/src/lib/components/sections/home/index.ts
  landing/src/lib/components/sections/home/problem-statement-section.svelte
  landing/src/lib/components/sections/home/steps-section.svelte
  landing/src/lib/index.ts
  landing/src/lib/utils/index.ts
  landing/src/routes/+layout.svelte
  landing/src/routes/+page.svelte
  landing/static/images/Inbox.png
  landing/static/images/conclude-and-close.png
  landing/static/images/cta-bg.png
  landing/static/images/feed.png
  landing/static/images/keyboard-shortcuts.png
  landing/static/images/logo.png
  landing/static/images/make-conversations.png
  landing/static/images/start-thread.png
  landing/static/images/thread-conversation.png
  landing/static/images/workspace.png
  landing/svelte.config.js
  landing/tsconfig.json
Labels: marketing

#21 Add workspace management features including creation, invitation hand…
  backend/bun.lock
  backend/package.json
  backend/src/api/workspace-invitations/index.ts
  backend/src/api/workspaces/index.ts
  backend/src/db/schema.ts
  backend/src/utils/email.ts
Labels: api

#27 Enhance layout structure for main and feed routes; add responsive styling
  app/src/routes/+layout.svelte
  app/src/routes/workspace/[workspaceId]/feed/+layout.svelte
Labels: bug, core
